name: flutter_forbidshot
description: A new Flutter plugin.
version: 0.0.2
author: qq326646683<326646683@qq.com>
homepage: https://github.com/qq326646683/flutter_forbidshot

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jinxian.flutter_forbidshot
        pluginClass: FlutterForbidshotPlugin
      ios:
        pluginClass: FlutterForbidshotPlugin

